### PR TITLE
Refactor discovery methods

### PR DESCRIPTION
**Pull request by loay**
### Description
Refactor discovery test cases

#### Related issues
connect to https://github.com/strongloop/loopback-connector/issues/15

### CODE REVIEW

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by loay** [comment]
@slnode test please

**Comment by loay** [comment]
@slnode test please

**Comment by loay** [comment]
@slnode test please

**Comment by rmg** [comment]
Currently failing on a linting error.
```
/home/jenkins/workspace/nb/loopback-connector-oracle~master/526b6e0f/test/oracle.discover.test.js
  30:9  error  Expected an assignment or function call and instead saw an expression  no-unused-expressions

✖ 1 problem (1 error, 0 warnings)
```

**Comment by loay** [comment]
@rmg There is that error now:
```
Error: libclntsh.so.12.1: cannot open shared object file: No such file or directory
```
even though the tests were running  minutes ago !

**Pull request merged**
