### PR TITLE
Run CI with juggler3

### PR DESCRIPTION
**Pull request by loay**
Connect to strongloop-internal/scrum-loopback#1042

### CODE REVIEW

**Comment by loay** [comment]
@rmg Hi Ryan,
PR is failing because apparently `oracledb` is not installed on either amazon-6 nor ubuntu-6

**Comment by loay** [comment]
@slnode test please

**Comment by loay** [comment]
test please

**Comment by loay** [comment]
`oracledb` is a dependency that should be installed by the package.. 
if it is missing then it is likely because it doesn't support node v6 yet
We need to do dig more into the oracle-installer and oracle-builder and see what works and how we get the proper image. ref: 
https://github.com/strongloop/loopback-connector-oracle/pull/77

**Comment by 0candy** [comment]
Changes LGTM.

**Comment by cjbj** [comment]
@loay node-oracledb supports Node 6.  See https://github.com/oracle/node-oracledb/blob/master/README.md

**Comment by loay** [comment]
@cjbj Thanks. 
Yeah I tried it in the above mentioned pr.

**Pull request merged**
