### PR TITLE
Use fetchAsString for CLOB

### PR DESCRIPTION
**Pull request by raymondfeng**
### Description

This PR uses `oracledb.fetchAsString` and `oracledb.fetchAsBuffer` options to simplify CLOB/BLOB reading.

#### Related issues

- None

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by jannyHou** [comment]
The 3 clob tests in `test/oracle.clob.test.js` fail due to 
> 1) Oracle connector should support clob size < 4000 chars:
     Uncaught Error: NJS-003: invalid connection

PTAL.

**Comment by raymondfeng** [comment]
@jannyHou These tests are passing in my local test. Can you try too?

**Comment by cjbj** [comment]
Note there are [upper size limitations](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#querying-lobs) if the Oracle Client is 11.2.  The Oracle Client 12 is OK.  And a future node-oracledb v2 won't have the limitation with 11 or 12.

**Comment by raymondfeng** [comment]
@jannyHou It seems the issue only happens with `oracledb@1.11.x`. Upgrading to `oracledb@1.12.0` and above fixes the problem. We probably have to rebuild the binary bundle.

**Comment by jannyHou** [comment]
@raymondfeng sounds good, Biniam helps me setup the testing ENV and we might need a new oracleUrl in https://github.com/strongloop/loopback-connector-oracle/blob/fc7c148249cd4420be8dde8838a1a976e8a21876/package.json#L22 for oracledb@^1.12.x

**Comment by cjbj** [comment]
fetchAsString was introduced in 1.12.  fetchAsBuffer was introduced in 1.13.  You will want 1.13.1.

**Pull request merged**
