### PR TITLE
Move the test command from run-tests to package.json test script for generating test result

### PR DESCRIPTION
**Pull request by smartmouse**
In order to generate the test result xunit.xml, we need to invoke the mocha test command directly in the test script in package.json.

### CODE REVIEW

**Comment by cgole** [comment]
@altsang should this have the #community contribution label? These changes are made by the qe-team, so we have test result numbers from Jenkins in order to have better reporting.

**Comment by altsang** [comment]
I don't believe so, was it accidentally labeled as such by me?

**Comment by cgole** [comment]
yeah, but thats fine. I deleted it.

**Comment by jannyHou** [comment]
@raymondfeng @rmg Could you take a look do we need to "invoke the mocha test command directly in the test script" ? Just one line's change. Thanks.

**Comment by rmg** [comment]
The way StrongLoop's CI works, it will do the `PATH`/`LD_LIBRARY_PATH`/`DYLD_LIBRARY_PATH` manipulation for you.

From a CI perspective, the package.json line should be:
```json
"test": "mocha -R spec --timeout 12000 --require ./test/init/init.js"
```
and then the `run-tests` script can replace it's mocha line with `npm test`.

This would require devs to run `./run-tests` instead of `npm test`, which may not be acceptable to devs.

**Comment by jannyHou** [comment]
Thank you @rmg . 
@smartmouse could you check Ryan's comment https://github.com/strongloop/loopback-connector-oracle/pull/51#issuecomment-209044712, thanks:)

**Comment by jannyHou** [comment]
Closing it due to out-of-date change.

**Pull request closed without merging**
