### PR TITLE
fix: remove UTC offset

### PR DESCRIPTION
**Pull request by hacksparrow**
Removes UTC offset

#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by ataft** [comment]
What happened to this PR? It doesn't look like the removal of UTC made it into master.

**Comment by hacksparrow** [comment]
It was for fixing an issue which turned out to be something else.

**Comment by ataft** [comment]
How did you fix the timezone issue you were having?

I'm having an issue with Oracle only, all the other databases (Postgres, My SQL, SQL Server) work fine. As I understand it, the NodeJS oracledb sets and gets DATE types in local time. Time zone is not stored in the date object, so then getting with UTC results in a time that's 8 hours ahead for me (Standard Pacific Time). 

I tried everything from different data types (timestamps) to time zone session settings, nothing worked. Then I found the `getUTC` logic in `dateToOracle()` from oracle.js. Removing the UTC part fixed the problem.

Here are the docs that informed me of the way Oracle and the NodeJS driver deal with time zones:
- https://oracle.github.io/node-oracledb/doc/api.html#-15163-fetching-dates-and-timestamps

- https://jsao.io/2016/09/working-with-dates-using-the-nodejs-driver/#persisting-and-fetching-datetime-values

**Comment by hacksparrow** [comment]
I didn't need to fix it as I was facing this error only on my local machine but it was fine on CI. I assume you'll have to know the timezone of the stored date and offset it with yours on in the result object.

**Comment by ataft** [comment]
That approach could work as a hack, but is not going to work in a database agnostic environment and would require a lot of manual work. If you [read up](https://oracle.github.io/node-oracledb/doc/api.html#-15163-fetching-dates-and-timestamps) on the node-oracledb package, you'll understand the following:

> DATE, TIMESTAMP, TIMESTAMP WITH LOCAL TIME ZONE, and TIMESTAMP WITH TIME ZONE columns are fetched as TIMESTAMP WITH LOCAL TIME ZONE using the session time zone

When this connector forces UTC, it is making a big presumption that is incorrect unless the session time zone is also UTC. Given that `loopback-connector-oracle` hard codes and forces UTC, I believe that setting `process.env.ORA_SDTZ = 'UTC';` will make things work as expected. Preliminary testing shows that it works.

@raymondfeng I'm happy to work with you to fix this connector, or fine to use this workaround if it's too low priority.

**Comment by fubz** [comment]
Any update on how you got around this @ataft ?  I tried setting process.env.ORA_SDTZ = 'UTC' ; however, my Date objects still get offset twice.  
I create a timestamp in EST  .e.g 12:00 PM EST, this package through loopback converts my time stamp to 17:00 UTC, which the database then interprets as 17:00 EST

**Comment by ataft** [comment]
@fubz Sorry, setting ORA_SDTZ worked for the few instances I had. You could try forking this repo and making the changes in the PR (i.e. removing UTC from the get() functions).

**Pull request closed without merging**
