### PR TITLE
Update deps to loopback 3.0.0 RC

### PR DESCRIPTION
**Pull request by bajtos**
Connect to strongloop-internal/scrum-loopback#1063

### CODE REVIEW

**Comment by bajtos** [comment]
test please

**Comment by bajtos** [comment]
@loay @0candy @jannyHou @superkhau Could you please take a look at the test failures? Are they relevant? Looks like https://github.com/strongloop/loopback-connector-oracle/pull/76 was landed with CI failing too, it's hard for me to tell whether this patch is ok to land or not.

**Comment by jannyHou** [comment]
I believe windows are failing due to same error(installing loopback-oracle-installer fails) with https://github.com/strongloop/loopback-connector-oracle/issues/75

Will take a look at the nvm machines.

**Comment by superkhau** [comment]
The non-cis ones are ignorable as they are the same as #59 as stated by @jannyHou. The CIS ones have been failing forever before your PR anyways. :ship:

**Comment by bajtos** [comment]
Thank you for the information.

> The CIS ones have been failing forever before your PR anyways

Could you please link here the user story to fix them?

**Comment by superkhau** [comment]
>Could you please link here the user story to fix them?

@loay I believe you are working on this, can you link to the issue here please?

**Pull request merged**
