### PR TITLE
fixed error in text in file README.md

### PR DESCRIPTION
**Pull request by ledinscak**
#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by dhmlau** [comment]
@ledinscak . thanks for submitting the PR.  Could you please sign the CLA? https://cla.strongloop.com/agreements/strongloop/loopback-connector-oracle

**Comment by b-admike** [comment]
@ledinscak Could you please sign the CLA, so we could land your patch? Thank you.

**Comment by kjdelisle** [comment]
@b-admike Can you recreate this PR separately and land it?

**Comment by b-admike** [comment]
@ledinscak Thank you for your contribution, but since you have not signed our CLA, I am closing this patch in favour of #150.

**Pull request closed without merging**
