### PR TITLE
Fix discoverModelProperties column order

### PR DESCRIPTION
**Pull request by ataft**
The SQL syntax in `buildQueryColumns` does not guarantee column order in a given table, sometimes resulting in incorrect column order. You need to `order by column_id`

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by ataft** [comment]
Any updates on this? Correct column order is a major issue, if you use discovery, and this is a very simple "no-brainer" fix...

**Comment by dhmlau** [comment]
@ataft, sorry about the late reply.  Could you please fix the commit linter error? 
```
**************************************************
**
**  Linting commit logs
**
**  1 problems found:
**    c05c36b - Fix discoverModelProperties column order: line 3 longer than 72 characters.
**
**************************************************
```
Also, your branch is out of date, please rebase it. Thanks.

**Comment by dhmlau** [comment]
Your change LGTM. _I think_ we're ok without having tests added.  
@strongloop/sq-lb-apex, what do you think?

**Comment by dhmlau** [comment]
Since I'll be going on vacation very soon, @hacksparrow, do you think you can help this PR to land when it's ready? Thanks!

**Comment by ataft** [comment]
@dhmlau I'm not sure what's causing the commit linting failure, my PR is only 1 line of code that is 33 characters long. I tried a rebase, doesn't look like it removed the error.

**Comment by hacksparrow** [comment]
@ataft Make sure the master branch has the latest changes (run`git pull origin master` on the master branch). Next, squash those 12 commits into one, then rebase and push.

**Comment by ataft** [comment]
Ah, too much work for a git newbie. I'll just maintain our fork... Thanks anyways!

**Comment by dhmlau** [comment]
@ataft, we don't have any other PR at the moment. Do you want to clone the repo and submit a PR again?

**Comment by hacksparrow** [comment]
@ataft it will be way simpler if you open a new PR from the latest master with just the changes in your last commit.

**Pull request closed without merging**
